### ISSUE TITLE
Warning: To locate the bad setState() At selector

### ISSUE THREAD

**Issue by syunto07ka** [facebookexperimental/Recoil#12]
A warning is occured where selector() used even though I write a code like one which is in the [official document here](https://recoiljs.org/docs/introduction/getting-started/#selector).

<img width="516" alt="スクリーンショット 2020-05-15 4 55 26" src="https://user-images.githubusercontent.com/37825725/81980341-61841500-9669-11ea-9427-390d04645eca.png">

this is my code

```
import React, { useEffect } from 'react';
import { atom, useRecoilState, useRecoilValue, selector } from 'recoil';

function RecoilApp() {
  useEffect(() => {
      console.log('test');
  });
  return(
    <div>
      Recoil App
      <TextInput />
      <CharCount />
    </div>
  );
}

const textState = atom({key: 'textState', default: ''});

function TextInput() {
  const [text, setText] = useRecoilState(textState);

  const onChange = event => {
    setText(event.target.value);
  }

  return(
    <div>
      <input type="text" value={text} onChange={onChange} />
      <br />
      Echo: {text}
    </div>
  );
};

function CharCount() {
  const count = useRecoilValue(countState);
  return <>Charset Count: {count}</>;
}

const countState = selector({
  key: 'countState',
  get: ({get}) => {
    const text = get(textState);
    return text.length;
  },
});

export default RecoilApp;

```

**Comment by ecreeth** [comment]
I have copied and pasted your code and it works. [See example in codesandbox](https://codesandbox.io/s/flamboyant-burnell-oiboe?file=/src/App.js)

**Comment by syunto07ka** [comment]
Thanks, ecreeth.
As you say that, my code works, but warning is occured in my browser.

Humm, I wonder that the codesandbox occured no warning at console like the image.

**Comment by dai-shi** [comment]
You need to try with react v16.13.1.
https://codesandbox.io/s/async-pine-gogdb

**Comment by slapner** [comment]
<img width="675" alt="Screen Shot 2020-05-15 at 9 19 01 AM" src="https://user-images.githubusercontent.com/20480013/82054627-37444e80-968d-11ea-8a47-9cdafc72052d.png">

The error is present in both the codesandbox links

**Comment by syunto07ka** [comment]
it's my installed dependences in pakcage.json.
so yeah, "16.13.1" is correct.

```
"dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "recoil": "0.0.7"
  },
```

**Comment by davidmccabe** [comment]
Thanks for reporting, I am investigating this.

**Comment by somonek** [comment]
Maybe something related to hot-loader?
I just had:
```
Warning: Cannot update a component from inside the function body of a different component.
```
then I removed the react-dom alias from my webpack config
```
alias: {
   'react-dom': '@hot-loader/react-dom',
},
```
and the error changes to

```
Warning: Cannot update a component (`Batcher`) while rendering a different component (`Header`). To locate the bad setState() call inside `Header`, follow the stack trace as described in https://fb.me/setstate-in-render
```

Header is my component name...

**Comment by djwglpuppy** [comment]
> Maybe something related to hot-loader?
> I just had:
> 
> ```
> Warning: Cannot update a component from inside the function body of a different component.
> ```
> 
> then I removed the react-dom alias from my webpack config
> 
> ```
> alias: {
>    'react-dom': '@hot-loader/react-dom',
> },
> ```
> 
> and the error changes to
> 
> ```
> Warning: Cannot update a component (`Batcher`) while rendering a different component (`Header`). To locate the bad setState() call inside `Header`, follow the stack trace as described in https://fb.me/setstate-in-render
> ```
> 
> Header is my component name...

I noticed also that setters stop working when hot reloading is set ... so having this related as well sounds like something worth exploring

**Comment by drarmstr** [comment]
Yes, we have a known issue with hot module loading at the moment.

**Comment by vandercloak** [comment]
Having the same issue. Thanks for reporting @syunto07ka and thanks for investigating @davidmccabe.

**Comment by lindskogen** [comment]
I have this issue and I'm not using react hot module loading.

**Comment by incepter** [comment]
The `Batcher`'s component's `setState` is the state setter that is being called, and the main cause is because `replaceState` from `RecoilRoot` is called when rendering subscribed components.

The warning was initially added to react on the `v16.13.0` release, and highlights an anti-pattern of the react mental model.

I cannot think of a way to make it work while maintaining the batching stuff.

Inlining the logic in the batcher's effect to `replaceState` solves the issue (along with `setTimeout` on the `notifyBatcherOfChange.current()`, but I don't believe that `setTimeout` is a reliable solution). While `RecoilRoot` wraps a context provider, a state inside it could be a solution, but we will return to the initial problem.

I understand that the main goal of the `Batcher` is to catch as many `setState` calls from subscribers as possible and delegate to react batching to gather `queuedComponentCallbacks` and optimize the count of re-renders.
Moreover, the subscribed component callback is the `forceUpdate` (state setter) of `useInterface` that is linked to subscribed components. So if many updates occur in a short duration, I prefer leaving react to handle the batching stuff rather than building a logic on top of it, and also because it is unstable.

Besides, the `replaceState` will notify the batcher only with the new state reference change, and as far as I read, this is the case when a new subscription occurs.

My question is, Shouldn't we drop the batcher and leave react manage the batching of state updates ? I mean, it is like an abstraction over an abstraction, or am I mistaking something?

I think to solve the problem without dropping the `Batcher`, a work loop that schedules when to flush the subscriptions is mandatory (may have its own problems though).

**Comment by jjrdn** [comment]
What if Batcher itself was rendered whenever a selector was rendered. eg, treat it as if it depends on all selectors. Then it would automatically queue its useEffect, and you would not need notify the Batcher of a change in replaceState, Batcher could test for the change when running it's useEffect. I think this also solves the "double render" whenever a selector changes dependencies.

**Comment by jjrdn** [comment]
I see now that replaceState is called under other conditions that are not part of a render.

This particular issue occurs because:
1. selectors are run during render
2. selectors update their dependencies when they run
3. updating dependencies calls replaceState
4. replaceState notifies the Batcher through use of setState on the Batcher, which happens during the render of the component that uses the selector

**Comment by davidmccabe** [comment]
I'm working on a big refactor where dependencies will not go through React state at all. That will fix this. In the meantime I don't see a an obvious workaround unfortunately.

**Comment by atanasster** [comment]
@davidmccabe - that would be great - pls post any updates when you have an ETA. Thanks again.

**Comment by avj2352** [comment]
I am getting the same error, In my case this error pops up if I use the selector variable as a dependency in my component's useEffect 
For eg:
in recoil:
```typescript
// get decoded URL of meetingId
export const getDecodedMeetingId = selector ({
    key: 'decodedMeetingIdState',
    get: async ({get}: any) => {
        const meetingId = get(meetingIdState);
        return decodeURI(meetingId);
    }
});
```

And then my component useEffect

```typescript
const meetingStatus = useRecoilValue(getDecodedMeetingId);
// side-effects
    useEffect(()=>{
        if (meetingStatus) {
            console.log('Begin Timer');
            startTimer();
        } else {
            setTimer(prev => prev);
        }
    },[meetingStatus]);
```

Hopefully this helps. If I am doing something wrong, please let me know.

**Comment by markerikson** [comment]
@davidmccabe I'm very curious - can you give any technical details on what you're doing and how it will improve CM compat?  My general understanding was that _any_ non-React-based state management approach will have issues with CM, because it can't tie in to React's ability to reorder state updates based on render priorities.

**Comment by dai-shi** [comment]
@markerikson That was my misunderstanding too, because they said at some point about considering the use of useMutableSource as one option.

https://github.com/facebookexperimental/Recoil/issues/5#issuecomment-628796942

In Recoil, state seems React based.

**Comment by avj2352** [comment]
Hi,
any ETA on this fix ? 
https://github.com/facebookexperimental/Recoil/issues/12#issuecomment-631238293

**Comment by jaredpalmer** [comment]
Confirming Recoil breaking hmr/fast refresh.

**Comment by farukg** [comment]
Hi, i found this comment from react-final-form where they had a similar issue and solved it:
https://github.com/final-form/react-final-form/issues/751#issuecomment-606212893

Hope this helps

**Comment by mphung97** [comment]
I have the same issue

**Comment by markstock7** [comment]
I  think **replaceState** shouldn't cause **Batcher** update when we call **getRecoilValueAsLoadable**, since **getRecoilValueAsLoadable** just get value from RecoilNode for computing derived value. I think the following code would work, But I am not for sure. @davidmccabe

```` javascript
const replaceState = (replacer, shouldNotNotifyBatcher) => {
    \\ other code
    if (shouldNotifyBatcher === true) return;
    nullthrows(notifyBatcherOfChange.current)();
};
````
````javascript
function getRecoilValueAsLoadable<T>(
  store: Store,
  {key}: AbstractRecoilValue<T>,
): Loadable<T> {
  let result: Loadable<T>;
  // Save any state changes during read, such as validating atoms,
  // updated selector subscriptions/dependencies, &c.
  Tracing.trace('get RecoilValue', key, () =>
    store.replaceState(
      Tracing.wrap(state => {
        const [newState, loadable] = getNodeLoadable(store, state, key);
        result = loadable;
        return newState;
      }),
      true
    ),
  );
  return (result: any); // flowlint-line unclear-type:off
}
````

**Comment by yishuxin** [comment]
Same issue.

**Comment by n8sabes** [comment]
Hi @davidmccabe, Any ETA on this?

Inclusion of any `selector` in any FC whereby the selector calls `get` on an atom, generates this error. The simplest use case in my project is:

```typescript
//
// foobarState.ts
//
export const foo = atom<boolean>({ key: "foo", default: true });
export const bar = selector<boolean>({ key: "bar", get: ({ get }) => !get(foo) });
```

```typescript
//
// component.tsx
//
...
export default ((props) => {
    const foobar = useRecoilValue(bar);
    return <>Hello World</>
}
```

As an early adopter with high hopes for this project, I'm migrating away from Redux to Recoil!! Crossing fingers to see Recoil "stable enough" for our beta in a few months.

Thanks for your efforts on this!!

**Comment by Tatamethues** [comment]
I got his warning because I used a selector get another async selector get. Some example code
```
export const asyncSelector = selector>({
    key: 'AsyncSelector ',
    get: async ({ get }) => {
        const response = await fakeData();
        const data = await response.json();
        await new Promise((resolve) => {
            setTimeout(() => {
                resolve();
            }, 200);
        });
      return data
    },
});

export const getAsyncSelector= selectorFamily({
    key: 'GetAsyncSelector',
    get: (params) => ({ get }) => {
       return get(asyncSelector ).slice(params);
    },
});
```

**Comment by ZitRos** [comment]
Also encountered this warning today, decided to step back to `react@16.12.0` and `react-dom@16.12.0` in the meantime. Thanks guys for your work, this library looks very promising!

**Comment by khanh19934** [comment]
Any update for this issue :( i try to add this to new project instead of redux ...

**Comment by MomchilKolev** [comment]
I'm using recoil to store a web3 contract and this line causes the error:
`const contract = useRecoilValue(contractState);`

A quick fix is:
`let contract = Promise.resolve(useRecoilValue(contractState)).then(c => contract = c);`
- A temporary fix at best.

The library is pretty fun to work with so thank you guys for all the effort :)

**Comment by Holybasil** [comment]
```js
// store.js
export const todoListTypeState = atom({
  key: "todoListTypeState",
  default: "snack",
});

export const todoListState = atom({
  key: "todoListState",
  default: [
    { type: "snack", content: "cake" },
    { type: "drink", content: "water" },
  ],
});

export const todoListSelector = selector({
  key: "todoListSelector",
  get: ({ get }) => {
    const type = get(todoListTypeState);
    const todoList = get(todoListState);
    return todoList.filter((item) => item.type === type);
  },
  set: ({ set }, newValue) => {
    set(todoListState, newValue);
  },
});

// Todo.js
const todoList = useRecoilValue(todoListState); //  :} good
const [typedTodoList, setTodoList] = useRecoilState(todoListSelector); //  :{ warning
```
waitting...

**Comment by andrecrts** [comment]
same issue here. Thanks for your work.

**Comment by MaxmaxmaximusGitHub** [comment]
I found such a workaround, in child component i change parent component statу with `useEffect`:

```javascript
  const [ref, dimensions] = useDimensions()
  const {setDimensions} = useContext(InventarContext)

  // bad
  setDimensions(dimensions)

  // good
  useEffect(() => {
    setDimensions(dimensions)
  })
```

**Comment by eLeontev** [comment]
Looks like for now we need to live (and can) with such warning till Recoil team will provide refactored version of `Batcher`.

For now the warning is valid and based on adding new validation-warning from React team to highligh anti-pattern to use `useState` setter out of component which happens in this place.
![image](https://user-images.githubusercontent.com/15786916/86759516-415f4980-c04d-11ea-914e-a03db8217c2d.png)

Downgrading React version to 16.12 will remove this issue if it annoying.

New warning React 16.13: https://ru.reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-some-updates-during-render
The details: https://github.com/facebook/react/issues/18178#issuecomment-602327720.

imho: any hacks and workaround will lead to complexity increasing and unexpected issues and it looks like a waste of time since the goal of this warning is only notify about the issue. And the fix should be centralized at least in this case.

**Comment by inlet** [comment]
Yep, same issue here.. it looks like the warning is only shown using selectors, pure atoms seems to be working without a warning.

Looking forward to a fix, thanks for all the hard work!

**Comment by arakir** [comment]
I have the same issue when an atom has a Promise as a default value.

**Comment by natew** [comment]
Should we track the HMR issue separately? For us that is the bigger blocker.

**Comment by drarmstr** [comment]
@natew - there is #247 for HMR

**Comment by dvkndn** [comment]
@drarmstr look like https://github.com/facebookexperimental/Recoil/pull/463 should fix this?

**Comment by DaniCastel** [comment]
I found this when:
- I had a setState in parent component (e.g const [state, _setState_] = useState({})
- I passed this setState to a child component and used it in a onClick={setState("value")}
- I solved this problem adding the arrow function.

**Comment by vivek12345** [comment]
do we have a fix for this? I am facing a similar error. Using recoil selector for an async call.

**Comment by drarmstr** [comment]
Also [this commit](https://github.com/facebookexperimental/Recoil/commit/856c561e989ae5b89c4b137fed87fe2c9ae0921f) and #399 help.  These should limit to situations we see the warning, but it can still show up and we need to resolve that with React.

**Comment by mehul-oscod** [comment]
> I have copied and pasted your code and it works. [See example in codesandbox](https://codesandbox.io/s/flamboyant-burnell-oiboe?file=/src/App.js)

did you tried in CRA or custome react App?

**Comment by shabanbx** [comment]
Hi any fix on this issue?

**Comment by nikolasveneti** [comment]
NextJS encountering the error `Cannot update a component (`Batcher`) while rendering a different component (xxx)` only in development e.g. HMR - haven't seen it yet on after built.

**Comment by el-angel** [comment]
@nikolasveneti because production build does not log warnings

**Comment by mattmogford-alcumus** [comment]
Surprised there's been no updates on Recoil since June.
I've just started using it and it is almost life changing.
This pescy warning is annoying and hoping it will be fixed soon?

**Comment by dvkndn** [comment]
@mattmogford-alcumus I completely agree that Recoil is life changing :D However it's not fair to say there's been no updates. There are quite frequent updates to master and I believe the team will eventually get to fix this issue :D There are several related commits already

**Comment by mattmogford-alcumus** [comment]
> @mattmogford-alcumus I completely agree that Recoil is life changing :D However it's not fair to say there's been no updates. There are quite frequent updates to master and I believe the team will eventually get to fix this issue :D There are several related commits already

I just saw the comment from @davidmccabe talking about the re-work and subsequent fix.
So that is great news!
GitHub should have a way for Contributors to 'pin' an important tweet such as that to the top, sometimes there is a lot of chaff to wade through to find the important information.
I did mean updates as in a tagged version, but yes that was unfair to say with all the work on issues etc... aaand I'm adding to the chaff!

**Comment by hayyaun** [comment]
This also happened for me in a case in which a component was rerendering too fast.

**Comment by Qquanwei** [comment]
This happen because my component use `useRecoilValue(selector)`

**Comment by emrekara37** [comment]
Any update for this issue

**Comment by 8detect** [comment]
> Any update for this issue

unfortunately not yet ! so live with the warning without any hacking around ( should not ) ! the error must be fixed in the core of the lib not working around , so until then just ignore the warning, at least it works and nothing crashes (hopefully), i still use it in my beta project. I forgot to mention that i use snowpack and so annoyed that the package has not supported ES module, hope the author fix it soon in late of this month because Recoil is really cool !

**Comment by mmmoli** [comment]
Fix is in the v0.11 release so keep watch for that.

Proposed: 15-Sep-2020 (https://github.com/facebookexperimental/Recoil/issues/534#issuecomment-691580341)

**Comment by adrianbw** [comment]
I'm seeing this in 0.0.11 still. Here's a sample set of tests that are throwing it:
```
describe("FertigationContainer", () => {
  it("renders expected markup", () => {
    const { container } = mount();
    expect(container).toMatchSnapshot();
  });
  it("does not have accessibility violations", async () => {
    const { container } = mount();
    const results = await axe(container);
    expect(results).toHaveNoViolations();
  });
});
```

**Comment by philohelp** [comment]
Fixed in v0.0.13
Youhouhou

**Comment by yukitaka13-1110** [comment]
v0.0.13 works for me!
Excellent!!

**Comment by 8detect** [comment]
confirmed : all fixed : the warning; useRecoilState bug with writable atom ( selector ) ; ESM support, web_modules compatible for snowpack. Thank you !

**Comment by adrianbw** [comment]
Can I see example of a test that's working for someone? I'm now on 0.0.13 and seeing the Batcher warning on this:
```typescript
describe("IrrigationEditTable", () => {
  it("renders correctly", () => {
    let wrapper;
    act(() => {
      wrapper = renderedComponent();
    });
    expect(wrapper).toMatchSnapshot();
  });
});
```

**Comment by akshayDatacode** [comment]
I am Also Facing the same warning in my console

**Comment by hatpick** [comment]
@drarmstr @davidmccabe I can see that 0.13 is published on npm, but it's not listed under releases page here, can we see a change log?

**Comment by sidferreira** [comment]
this helped me to solve my issue. 
I had a callback inside a memoed component but it wasn't using `useEffect`

**Comment by drarmstr** [comment]
> @drarmstr @davidmccabe I can see that 0.13 is published on npm, but it's not listed under releases page here, can we see a change log?

Yes, #581 is still landing

**Comment by Tobijudah** [comment]
> I found this error when:
> 
> * I had a setState in parent component (e.g const [state, _setState_] = useState({}))
> * I passed this setState to a child component and used it in a onClick={setState("value")}
> * I solved this problem adding the arrow function in the onClick call

this worked for me. @DaniCastel any reason an arrow function had to be used. React newbie here

**Comment by pranavkumar389** [comment]
In my case, it's because I was mutating a prop value in the child component.

**BEFORE**
```
import React from 'react';

const Todo = ({ text, todo, todos, setTodos }) => {
  
  const deleteHandler = () => {
    setTodos(todos.filter(el => el.id !== todo.id)) // mutauing a prop here
  }

 return (
   <div className="todo">
     <li className="todo-item">{text}</li>
     <button className="complete-btn"><i className="fas fa-check"></i></button>
     <button className="trash-btn" onClick={deleteHandler()}><i className="fas fa-trash"></i></button>
   </div>
 );
}

export default Todo;
```

**AFTER**
``` 
import React from 'react';

const Todo = ({ text, todo, todos, setTodos }) => {

  const todosCopy = JSON.parse(JSON.stringify(todos));
  
  const deleteHandler = () => {
    setTodos(todosCopy.filter(el => el.id !== todo.id)) // mutating a copy of prop value here
  }

 return (
   <div className="todo">
     <li className="todo-item">{text}</li>
     <button className="complete-btn"><i className="fas fa-check"></i></button>
     <button className="trash-btn" onClick={deleteHandler}><i className="fas fa-trash"></i></button>
   </div>
 );
}

export default Todo;
```

**Comment by FezVrasta** [comment]
@pranavkumar389 `Array.prototype.filter` doesn't mutate its original array.

**Comment by delucca** [comment]
Any updates at this issue?

I'm facing it in my custom `IntlProvider`. In a nutshell, I'm wrapping it (from `react-intl`) in a custom component that stores the selected locale in my Recoil state for further usage by my own selectors.

Here is a sample code:

```ts
import React, { ReactElement } from 'react'
import { IntlProvider } from 'react-intl'
import { OptionalIntlConfig } from 'react-intl/src/components/provider'
import { useSetRecoilState } from 'recoil'

import { locale as localeAtom } from 'state/recoil/intl/locale'

export interface RecoilIntlProviderProps extends OptionalIntlConfig {
  children: ReactElement
}

const RecoilIntlProvider = (props: RecoilIntlProviderProps): ReactElement => {
  const setRecoilIntl = useSetRecoilState(localeAtom)
  setRecoilIntl(props.locale)

  return <IntlProvider {...props} />
}

export default RecoilIntlProvider
```

And my atom:

```ts
import { atom } from 'recoil'

import { PREFIX } from './constants'

const KEY = `${PREFIX}::LOCALE`

export const locale = atom<string>({
  key: KEY,
  default: '',
})
```

To make it work, you need to use the following tree in your `app.js(ts)`:

```ts
    <RecoilRoot>
      <RecoilIntlProvider locale={locale ?? 'pt-BR'} messages={messages}>
        <Component {...pageProps} />
      </RecoilIntlProvider>
    </RecoilRoot>
```

Looking forward for a fix in this issue :)

**Comment by nickhow83** [comment]
I had a similar issue and it turns out the problem was how I was using it.  I had an async selector which derived a value from an atom.

For example, I had a User atom and a Roles async selector.  Whenever the User updated (should really only happen once) then the Roles would be loaded from the API for that User.

However, I used a hook to retrieve the User and every time the hook ran, it updated the User (in the hook), which in turn triggered a Roles API request.

Simple fix was to set the User atom from a useEffect, with the User in the deps array.

**Comment by chroth7** [comment]
I had a similar issue just now and solved it the very same way @nickhow83 did. So in my case:
- rather easy fix
- rather cryptic error message
Great work on the lib though, really enjoy working with the model

**Comment by nickhow83** [comment]
> Any updates at this issue?
> 
> I'm facing it in my custom `IntlProvider`. In a nutshell, I'm wrapping it (from `react-intl`) in a custom component that stores the selected locale in my Recoil state for further usage by my own selectors.
> 
> Here is a sample code:
> 
> ```ts
> import React, { ReactElement } from 'react'
> import { IntlProvider } from 'react-intl'
> import { OptionalIntlConfig } from 'react-intl/src/components/provider'
> import { useSetRecoilState } from 'recoil'
> 
> import { locale as localeAtom } from 'state/recoil/intl/locale'
> 
> export interface RecoilIntlProviderProps extends OptionalIntlConfig {
>   children: ReactElement
> }
> 
> const RecoilIntlProvider = (props: RecoilIntlProviderProps): ReactElement => {
>   const setRecoilIntl = useSetRecoilState(localeAtom)
>   setRecoilIntl(props.locale)
> 
>   return <IntlProvider {...props} />
> }
> 
> export default RecoilIntlProvider
> ```
> 
> And my atom:
> 
> ```ts
> import { atom } from 'recoil'
> 
> import { PREFIX } from './constants'
> 
> const KEY = `${PREFIX}::LOCALE`
> 
> export const locale = atom<string>({
>   key: KEY,
>   default: '',
> })
> ```
> 
> To make it work, you need to use the following tree in your `app.js(ts)`:
> 
> ```ts
> <RecoilRoot>
>   <RecoilIntlProvider locale={locale ?? 'pt-BR'} messages={messages}>
>     <Component {...pageProps} />
>   </RecoilIntlProvider>
> </RecoilRoot>
> ```
> 
> And my warning in the console log:
> 
> ```
> Warning: Cannot update a component (`Batcher`) while rendering a different component (`RecoilIntlProvider`). To locate the bad setState() call inside `RecoilIntlProvider`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
> RecoilIntlProvider@webpack-internal:///./components/Base/RecoilIntlProvider/recoil-intl-provider.tsx:23:87
> RecoilRoot@webpack-internal:///../.yarn/$$virtual/recoil-virtual-0c2fe5134c/0/cache/recoil-npm-0.1.2-9a0edbd2b9-c69105dd7d.zip/node_modules/recoil/es/recoil.js:1722:1
> BudApp@webpack-internal:///./pages/_app.tsx:70:19
> ErrorBoundary@webpack-internal:///../.yarn/$$virtual/@next-react-dev-overlay-virtual-ba69454c0b/0/cache/@next-react-dev-overlay-npm-10.0.0-5db65d7be6-f38cbe7f69.zip/node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47
> ReactDevOverlay@webpack-internal:///../.yarn/$$virtual/@next-react-dev-overlay-virtual-ba69454c0b/0/cache/@next-react-dev-overlay-npm-10.0.0-5db65d7be6-f38cbe7f69.zip/node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:20
> Container@webpack-internal:///../.yarn/$$virtual/next-virtual-6f4174843d/0/cache/next-npm-10.0.0-82dc2f1372-c01b177cb2.zip/node_modules/next/dist/client/index.js:173:20
> AppContainer@webpack-internal:///../.yarn/$$virtual/next-virtual-6f4174843d/0/cache/next-npm-10.0.0-82dc2f1372-c01b177cb2.zip/node_modules/next/dist/client/index.js:641:18
> Root@webpack-internal:///../.yarn/$$virtual/next-virtual-6f4174843d/0/cache/next-npm-10.0.0-82dc2f1372-c01b177cb2.zip/node_modules/next/dist/client/index.js:757:18
> ```
> 
> Looking forward for a fix in this issue :)

Your provider is setting the state in the render. If you put it in a useEffect then the problem will go away :)

It seems it’s not a problem with the library but the understanding of how it’s used in the react lifecycle.

If you had a useState for example, you wouldn’t update that directly in the render method, you’d do it inside an effect.

**Comment by onur-kaplan** [comment]
@syunto07ka I have the same problem, but when I run the "npm run prod" code, this error disappears. I only see this error in development mode.

**Comment by nickhow83** [comment]
> @syunto07ka I have the same problem, but when I run the "**npm run prod**" code, this error disappears. I only see this error in development mode.

Running in prod mode only hides the errors, it still happens.  Have a look at my comment above and it should explain what needs to be done

**Comment by JituG22** [comment]
In my case  this problem was  with "redux" reducer file  where i was created some bad practice..!
myReducer.js
 switch(action.type){

  case "Any_Case":
                return {
                    data:action.payload,
                }
}

If you see in above code snippet i was miss out  to add in return  **"...state"** which was the coz issue produce. 
If you understand you issue that if you not add **"...state"** in return it will whole state replace with new state and all **previous state get oversrite with new one state** which Coz to producer issue "Cannot update a component (`xxx`) while rendering a different component (`xxx`)."

**So here is the Solution** 
myReducer.js
 switch(action.type){

  case "Any_Case":
                return {
                    **...state,** /* make sure add this line of code */
                    data:action.payload,
                }
}

**Comment by delucca** [comment]
I'm facing this error for some months for now, no idea how to fix it?

Until now it was not causing any trouble in my application at all. And since prod "hides" those errors, it was not a big deal. But, now I'm coding some unit tests for bigger modules (using Jest), and this kind of error is causing strange behavior such as one component inside the component tree is correctly updated with the new data (after a setState) but other component won't.

**Comment by nickhow83** [comment]
> I'm facing this error for some months for now, no idea how to fix it?
> 
> Until now it was not causing any trouble in my application at all. And since prod "hides" those errors, it was not a big deal. But, now I'm coding some unit tests for bigger modules (using Jest), and this kind of error is causing strange behavior such as one component inside the component tree is correctly updated with the new data (after a setState from a parent component) but other component isn't.
> 
> To give more details, the component I'm trying to code has basically three parts:
> 
> 1. The parent, which does a GraphQL query and updates my Recoil state after the query finishes
> 2. A child, that renders part of that query data
> 3. Another child (at the same level as the latest child) that contains a simple component (grandchild of the parent) which renders another part of the query data
> 
> While running the app, it works like a charm. It throws that Batcher error, but it works.
> 
> But, while testing it with Jest + Enzyme, it simply won't work. The first child is updated with the new state, but the second one isn't.
> 
> In the parent component I update the recoil state with the `onCompleted` callback option of Apollo (but the same issue happens with `useEffect`.
> 
> Here are a minimal reproduction of those 3 components:
> 
> parent:
> 
> ```ts
> const SettingsAccount = () => {
>   const myUserID = useRecoilValue(meAtom)
>   const setUser = useSetRecoilState(userAtomFamily(myUserID))
>   const [getUserData, { loading, variables }] = useLazyQuery<GetUserDataQuery>(
>     queries.GET_USER_DATA,
>     {
>       onCompleted: (data) => setUser(data.user),
>       variables: {
>         id: myUserID,
>       },
>     },
>   )
> 
>   useEffect(() => {
>     if (myUserID && myUserID !== variables?.id) getUserData()
>   }, [myUserID, getUserData, variables])
> 
>   return (
>     <Flex py={4} gridGap={6} direction="column" w="full">
>       <SettingsAccountHeader userID={myUserID} loading={loading} />
>       <Divider borderColor="black.200" />
>       <SettingsAccountBody userID={myUserID} loading={loading} />
>     </Flex>
>   )
> }
> ```
> 
> child 1 (SettingsAccountHeader)
> 
> ```ts
> const SettingsAccountHeader = ({ userID, loading }: SettingsAccountHeader) => {
>   const user = useRecoilValue(userAtomFamily(userID))
>   const isLoaded = !loading && Boolean(user)
> 
>   return (
>     <Flex gridGap={4} alignItems="center">
>       <UserAvatar size="xl" name={user?.fullName} src={user?.picture} />
> 
>       <Flex direction="column" gridGap={4}>
>         <Flex direction="column" gridGap={1}>
>           <Skeleton isLoaded={isLoaded} {...buildSkeletonMinSize(isLoaded, 180, 24)}>
>             <Heading as="h2" color="black.900" fontSize="xl" fontWeight={500}>
>               {user?.fullName}
>             </Heading>
>           </Skeleton>
> 
>           <Skeleton isLoaded={isLoaded} {...buildSkeletonMinSize(isLoaded, 220, 18)}>
>             <Text color="gray.400" fontSize="md" fontWeight={400}>
>               {user?.role}
>             </Text>
>           </Skeleton>
>         </Flex>
> 
>         <UserTeamTags userID={userID} loading={loading} />
>       </Flex>
>     </Flex>
>   )
> }
> ```
> 
> child 2 (SettingsAccountBody)
> 
> ```ts
> const SettingsAccountBody = ({ userID, loading }: SettingsAccountBodyProperties) => (
>   <Flex direction="column" gridGap={6}>
>     <SettingsAccountBodyPersonalInformations userID={userID} loading={loading} />
>     <Divider borderColor="black.200" />
>     <SettingsAccountBodySocialMedia userID={userID} loading={loading} />
>   </Flex>
> )
> ```
> 
> first grandchild (SettingsAccountBodyPersonalInformations)
> 
> ```ts
> const SettingsAccountBodyPersonalInformations = ({
>   userID,
>   loading,
> }: SettingsAccountBodyPersonalInformationsProperties) => {
>   const user = useRecoilValue(userAtomFamily(userID))
>   const intl = useIntl()
> 
>   const isLoaded = !loading && Boolean(user)
> 
>   return (
>     <Stack direction="column" spacing={6}>
>       <SettingsAccountBodySectionTitle
>         title={intl.formatMessage(messages.sectionTitle)}
>         subtitle={intl.formatMessage(messages.sectionSubtitle)}
>       />
> 
>       <Stack direction="column" spacing={4}>
>         <Flex>
>           <EditableField
>             label={intl.formatMessage(messages.firstFieldLabel)}
>             value={user?.firstName}
>             isLoaded={isLoaded}
>             flexGrow={1}
>           />
>           <EditableField
>             label={intl.formatMessage(messages.secondFieldLabel)}
>             value={user?.lastName}
>             isLoaded={isLoaded}
>             flexGrow={1}
>           />
>         </Flex>
> 
>         <EditableField
>           label={intl.formatMessage(messages.thirdFieldLabel)}
>           value={user?.nickname}
>           isLoaded={isLoaded}
>         />
> 
>         <EditableField label={intl.formatMessage(messages.fourthFieldLabel)}>
>           <UserTeamTags userID={userID} loading={loading} />
>         </EditableField>
> 
>         <EditableField
>           label={intl.formatMessage(messages.fifthFieldLabel)}
>           value={user?.role}
>           isLoaded={isLoaded}
>         />
> 
>         <EditableField
>           label={intl.formatMessage(messages.sixthFieldLabel)}
>           value={user?.gender}
>           isLoaded={isLoaded}
>         />
> 
>         <EditableField
>           label={intl.formatMessage(messages.seventhFieldLabel)}
>           value={user?.about}
>           isLoaded={isLoaded}
>         />
>       </Stack>
>     </Stack>
>   )
> }
> ```
> 
> It is a simple implementation, with just a single component changing the state (the root parent), but it still wont work. If I do `console.log(user)` inside of `SettingsAccountHeader` (child 1) I can get the correct data. But, if I do the same `console.log(user)` inside `SettingsAccountBodyPersonalInformations` (the grandchild) it prints undefined.
> 
> It does not make sense. Since both components are only reading the state (without changing it at all) why they can't print the correct results in my test environment?
> 
> Just for the record, `SettingsAccountBodySocialMedia` component (the component I've not shared here, is almost the same as grandchild 1, it does not mutate state or anything.

it might be that in your grandchild, you're passing userID as a prop, if that the atom?  If not, then you're probably shadowing the atom/atomFamily you've (possibly) defined higher in the code... if it's not the atom, then recoil won't know how to use it.

I know it doesn't fix the error but it should fix your data being undefined.

**Comment by AndrewJudson** [comment]
If I get this warning and everything else is working as expected, should I be concerned? Does it indicate a memory leak or something else that will affect the performance of the app?

**Comment by delucca** [comment]
> If I get this warning once and everything else is working as expected, should I be concerned? Does it indicate a memory leak or something else that will affect the performance of the app?

I was in your shoes last year. I was getting this warning, and everything else was ok. My problem was when I started coding unit tests. Them, this warning was preventing my recoil state from being updated on test environments.

So, this is still problem.

**Comment by ryancwalsh** [comment]
I'm having this problem too!

**Comment by GTOsss** [comment]
I have the same problem. At the same time, the application works correctly and no bugs are detected

**Comment by thexpand** [comment]
For me it was a stupid mistake (typo). I had a memoized function, which inside of its dependencies had a Recoil setter being invoked/called, instead of just passed in the deps array.

Problematic code:
```js
const [, setHasUnsavedChanges] = useRecoilState(hasUnsavedChangesState);

const save = useCallback(
    () => {
        // ...
    },
    [setHasUnsavedChanges()] // <--- Here's what was wrong, function was invoked, which is wrong
);
```

Fixed code:
```js
const [, setHasUnsavedChanges] = useRecoilState(hasUnsavedChangesState);

const save = useCallback(
    () => {
        // ...
    },
    [setHasUnsavedChanges] // <--- Here it is fixed
);
```

**Comment by alex-cory** [comment]
> I'm working on a big refactor where dependencies will not go through React state at all. That will fix this (and make it a lot more efficient, and is needed for CM). In the meantime I don't see a an obvious workaround unfortunately.

@davidmccabe Any idea when we can expect this refactor to be working?

**Comment by a-tonchev** [comment]
Same here on React 17.0.2 and recoil 0.3.1.

Is it safe to ignore this warning?

**Comment by gilvaju** [comment]
Same here on React 17.0.2 and recoil 0.3.1.

Is it safe to ignore this warning?

+1

**Comment by obadakhalili** [comment]
Same in React 17.0.2 and Recoil 0.3.1.

**Comment by codal-hkrishnani** [comment]
I was facing same issue, The fix worked for me was if u are doing  

> setParams/setOptions

 outside of useEffect then this issue is occurring. So try to do such things inside useEffect. It'll work like charm

**Comment by a-tonchev** [comment]
> I was facing same issue, The fix worked for me was if u are doing
> 
> > setParams/setOptions
> 
> outside of useEffect then this issue is occurring. So try to do such things inside useEffect. It'll work like charm

For me this does not fix the problem. Actually sometimes the warning appears, sometimes not. it is weird ...

**Comment by codal-hkrishnani** [comment]
> > I was facing same issue, The fix worked for me was if u are doing
> > > setParams/setOptions
> > 
> > 
> > outside of useEffect then this issue is occurring. So try to do such things inside useEffect. It'll work like charm
> 
> For me this does not fix the problem. Actually sometimes the warning appears, sometimes not. it is weird ...

Try to check in all screens, you might have add same code in multiple screen screens

**Comment by davidh99720** [comment]
I have the same issue. It is caused by setting pageTitle (displayed in explorer tab and history) in each component after routing using recoil. Fixed after centralizing the pageTitle logic in the root of component where pageTitle is rendered and get rid of the recoil setting action.

**Comment by feel5ny** [comment]
Same here on React 17.0.2 and recoil 0.3.1.

Is it safe to ignore this warning?

+2

**Comment by incepter** [comment]
No, it is not safe to ignore, it is against the model of react itself.

Your component while rendering tries to alter the state of another component, this couples both of them to each other and makes the render operation of your component non atomic and with side effects impacting other components.

Recoil uses some technique internally (for batching if my memory is good enough) that alters the state of components while rendering, and react tells us not to do this, so clearly you should not ignore the message.

AFAIK, it was related to selectors, but I remember only the initial ever code about recoil, I don't honestly know how this became and if there is a chance to solve this issue.

**Comment by Zasa-san** [comment]
+1 Having the same issue right now.
